# -*- coding: utf-8 -*-
"""Messy Data Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HLirrDRkAePmZnhBCdv3kPMI-xRsKix1

# **Import Libraries**
"""

import random
import pandas as pd
from datetime import datetime, timedelta

"""# **Predefine Values**"""

random.seed(42)
n = 500

first_names = ["Khushi", "John", "Aarav", "Emily", "Raj", "Sophia", "Michael", "Ananya", "Chris", "Neha"]
last_names = ["Bhoj", "Smith", "Patel", "Johnson", "Kumar", "Brown", "Davis", "Sharma", "Wilson", "Gupta"]

states = [
    "CA", "ca", "California", "CALIFORNIA", "AL", "AX", "HI",
    "NY", "ny", "New York", "NEW YORK", "SC", "NH", "IL", "OH",
    "TX", "tx", "Texas", "TEXAS", "DC", "CO", "MI", "VA", "MN",
    "FL", "fl", "Florida", "FLORIDA", "NJ", "NC", "nc", "WA",
    None
]

email_domains = ["gmail.com", "yahoo.com", "school.edu", "outlook.com"]

"""# **Random Value Generator Function**"""

def messy_name():
    fn = random.choice(first_names)
    ln = random.choice(last_names)
    name = f"{fn} {ln}"
    if random.random() < 0.3:
        return f"'{name}'"
    elif random.random() < 0.3:
        return f'"{name}"'
    return name

def messy_dob():
    start = datetime(1995, 1, 1)
    end = datetime(2005, 12, 31)
    dob = start + timedelta(days=random.randint(0, (end - start).days))
    formats = [
        dob.strftime("%m%d%Y"),
        dob.strftime("%m/%d/%Y"),
        dob.strftime("%m-%d-%Y %H:%M:%S"),
        dob.strftime("%m%d%y"),
    ]
    val = random.choice(formats)
    if random.random() < 0.3:
        return f"'{val}'"
    elif random.random() < 0.3:
        return f'"{val}"'
    return val

def messy_phone():
    return random.choice([
        f"{random.randint(100,999)}-{random.randint(100,999)}-{random.randint(1000,9999)}",
        f"+1{random.randint(1000000000,9999999999)}",
        f"1{random.randint(1000000000,9999999999)}",
        f"{random.randint(1000000000,9999999999)}"
    ])

def messy_email():
    if random.random() < 0.15:
        return None
    fn = random.choice(first_names).lower()
    ln = random.choice(last_names).lower()
    sep = random.choice([".", "_", ""])
    return f"{fn}{sep}{ln}@{random.choice(email_domains)}"

"""# **Creating Dataset**"""

rows = []

for _ in range(n):
    rows.append({
        "student_name": messy_name(),
        "date_of_birth": messy_dob(),
        "state": random.choice(states),
        "mobile_number": messy_phone(),
        "email": messy_email(),
        "gpa": random.choice([
            round(random.uniform(2.0, 4.0), 2),
            None,
            f"{round(random.uniform(2.0, 4.0), 2)}"
        ])
    })

df = pd.DataFrame(rows)
path = "unclean_student_dataset.csv"
df.to_csv(path, index=False)